### ISSUE TITLE
[5.14-OOB] mbed-os-example-nfc\NFC_EEPROM failed when building with Online compiler

### ISSUE THREAD

**Issue by korjaa** [ARMmbed/mbed-os-example-nfc#44]
Board: DISCO_L475VG_IOT01A
Build failed to:
```
Error: L6200E: Symbol __ARM_use_no_argv multiply defined (by ../../build/NFC_SmartPoster/main.DISCO_L475VG_IOT01A.o and ../../build/NFC_EEPROM/source/main.DISCO_L475VG_IOT01A.o).
```

**Comment by jamesbeyond** [comment]
The example readme claims direct import is not working with online compiler:
https://github.com/ARMmbed/mbed-os-example-nfc#known-issues
Can this ticket been closed @korjaa

**Comment by korjaa** [comment]
This project is available for online compiler here https://os.mbed.com/teams/mbed-os-examples/code/mbed-os-example-nfc-EEPROM/. There is no mention on the mbed page that the project is not compatible with the online compiler.

I was just thinking the code on the mbed repository is cloned from here so I thought this could be the right place for this issue.

**Comment by jamesbeyond** [comment]
As the error suggested this example wasn't import to online compiler correctly, the online compiler imported  `main.cpp` from both `NFC_SmartPoster` and `NFC_EEPROM`.
Checking the mercurial repo `https://os.mbed.com/teams/mbed-os-examples/code/mbed-os-example-nfc-EEPROM/` the repo is correctly configured with one `main.cpp`. So I think the issue is on online compiler side. Could you move the defect to the online team ?

**Comment by korjaa** [comment]
I just tried again with mbed-os-5.14-rc2 and it works. So I'll close this.
